theme = 'ananke'
contentDir = 'content'
baseURL = 'https://lazarev.work'
languageCode = 'en-us'
title = 'YES'


[params]
sitename = "Alexanders Blog"


[[params.socialIcons]]
name = "linkedin"
url = "https://www.google.com"


[[params.socialIcons]]
name = "email"
url = "https://www.google.com"


[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
disable = true
[privacy.instagram]
disable = true
[privacy.twitter]
disable = true
[privacy.vimeo]
disable = true
[privacy.youtube]
disable = true